### ISSUE TITLE
Allow to travel with ships from one corner of the world to another

### ISSUE THREAD

**Issue by cbnolok** [Sphereserver/Source-experimental#147]
The current idea is to have the keywords WRAPX and WRAPY working like that:
WRAPX=Xs, Xe, Xd
Where: Xs is the starting (top-most) x coordinate of the wrap line, Xe is the ending x of the wrap line and Xd is the starting (top-most) X coordinate of the destination line (at the other corner of the world) where the ship will be teleported. The end of the destination line will be Xd + (Xe - Xs).
Similar working for WRAPY. The ship will be rotated specularly after the teleport.
Any better ideas?

**Comment by nefthon** [comment]
Does it need to rotate? if you get to WRAPX in the northern part of the map you will be moved to the shouthern one, but you will be sailing in the same direction or you will come back again to that WRAP, same for southern sailing , east, west, south-east ...

I would recommend to set WRAP MAX values to something like 30 tiles away to that limit, eg; WRAPDIST=30 this will make your ship move while being at X =30 or lower, X 7138 or lower for newer maps or 6114 on older ones, the same 30 or 4066 for Y values. The good point on this is that people with custom maps shouldn't require any additional setting since this will automatically adjust the limits.

That being said, on each ship movement should be placed 4 checks, one per each direction, if you reach north a loop for all the items and chars inside the ship doing a Move(DIR_S, g_MapList.GetY(m_map) - g_Cfg._iWrapDist);

**Comment by GitMadKing** [comment]
Those wrapx/y should be put in sphere ini so anyone could manage
autonomally. Think at custom maps.
Should be put attention to diagonal sailing. X+1 Y+1 / X+1 Y-1 / X-1 Y+1 /
X-1 Y-1.
Also fast sailing if is using two tiles at a time or is just going faster
but still with 1 tile per time.


Il giorno Mar 6 Nov 2018, 19:54 Javier González Ondina <
notifications@github.com> ha scritto:

**Comment by Ben1028** [comment]
This should be a very simple feature. I had something like this working on an old 55i server i believe using only scripts. Once you reach a certain point on the map, you are teleported to the other side, keeping direction and speed so that it seems like you are on a globe
