### ISSUE TITLE
increase damage and weaponspeed increase Problem

### ISSUE THREAD

**Issue by osmanozgene** [Sphereserver/Source-experimental#208]
They are not working anymore. Increase damage doesnt increase Existed damage and increase speed doesnt increase attack speed.

**Comment by cbnolok** [comment]
Are you testing it on players or on npcs? Or both?

**Comment by drk84** [comment]
For players only, it seems that the code;
`int iIncreaseDam = (int)GetPropNum(COMP_PROPS_CHAR, PROPCH_INCREASEDAM, true);
`
applies the INCREASEDAM property only when the property is set to the chardef, I have noticed this because the  size of _mPropsNum was always 6, and in the CHARDEF of c_man we have 6 properties defined:

1. INCREASEDEFCHANCEMAX
2.  RESPHYSICALMAX
3.  RESCOLDMAX
4. RESFIREMAX
5.  RESENERGYMAX
6. RESPOISONMAX

By adding INCREASEDAM to the chardef mProsNum size becomes 7 and damage is correctly increased.

So i think that the true value GetPropNum just check the CHARDEF instead of checking  the value on the character and then the chardef.
Settings the value to false seems to nothing.

**Comment by osmanozgene** [comment]
Hey nolok everything looks well but if you decrease your increasedam or any value to 0 it wont update itself. I mean Try this : 

.increasedam 50
.increasedam 40
.increasedam 0

you will see the problem.  You dont see the 0 value. You need .update or reopen your stat window.
