### ISSUE TITLE
something strange with HEIGHT Limitation 

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-experimental#265]
player rided on horse can't go to building with <20 height floor, i can't go to 19 heigth, just blocking steps
without horse can go to 16 for example

// Do not allow entering under roof being on horse?
MountHeight=0

have no this problem in #3056

**Comment by JulianUO** [comment]
Some UO decoration is set at FloorZ + 1, such as carpets, take a look at Britain's Inn. This makes impossible to walk on while riding a horse. Similar happens when you try to go into Britain's Sewers, since there's a stairs block (Height = 5) you won't be able to walk on.

But...
I fixed this in a easy way by lowering char's height on sphere_defs.scp (or defs_height.scp)
```
height_0190 12 //DEFNAME=c_man
height_0191 12 //DEFNAME=c_woman
height_0192 12 //DEFNAME=c_ghost_man
height_0193 12 //DEFNAME=c_ghost_woman
```
Setting it to 12 made it possible.
Can't remember how many height adds a horse.

**Comment by Seokotov** [comment]
ahh, never heard about this defs
just dont't have problems before latest update...
