### ISSUE TITLE
items not stacking correctly

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#318]
mainly ores and resources. same while f.e. mining, it is doing new stacks of same ore in backpack.
[![Screenshot from Gyazo](https://gyazo.com/cd1be261d6b00983b34813d0c9d9154c/raw)](https://gyazo.com/cd1be261d6b00983b34813d0c9d9154c)

**Comment by cbnolok** [comment]
If i'm mining, here it adds the new ore on the stack of the old ores of the same type (normal). When adding a single ore on another (on ground), the client doesnt' even send the request to the server, so it isn't sphere fault, sadly. I haven't checked, but the problem may be caused by some ore art tiles not having the pileable tiledata flag, while some others do have that.
