### ISSUE TITLE
custom housing

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#323]
also on vanilla scps
[![Screenshot from Gyazo](https://gyazo.com/70b201fff3675f894b4740c2a1693939/raw)](https://gyazo.com/70b201fff3675f894b4740c2a1693939)

**Comment by cbnolok** [comment]
Shouldn't that be the default behavior? Isn't that happening also on 56c or d?

**Comment by AtillaG1** [comment]
on corujas build it is doing everything OK. Even the stairs are different as we are used to.

**Comment by soulless320** [comment]
Yeah, deleting one tile shouldn't remove the whole floor, it not only removes the entire floor but it removes everything on the level as well, this includes walls and doors. :O

**Comment by cbnolok** [comment]
Clearly it shouldn't remove walls and the doors, though i'm not sure that it shouldn't remove the whole floor. I guess that on 56d issue #202 is still present (if the whole floor isn't removed there), and in the attached video you can see that (at least in that case) the client removes the whole floor (that bug was in fact caused by the client removing the whole floor, but sphere internally removing only the targeted tile).

**Comment by cbnolok** [comment]
Actually, by testing more, it looks like the whole floor is removed only if it's invalid, gotta think about how to solve this now

**Comment by AtillaG1** [comment]
missing floor is good.
