### ISSUE TITLE
@UserChatButton not firing for button

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-experimental#326]
@UserChatButton not firing for button
justopen chat dialog even if 

`ON=@UserChatButton
SRC.SMSG Disabled    
RETURN 1`

**Comment by JulianUO** [comment]
Hi,
From what I can see here, the ChatButton packet is sent only once, at least in newer clients.
It is used mostly to register the name of the char in the chat system.
Try creating a new character and you will see, only the first time is triggered.

The menu is client-side.

**Comment by Seokotov** [comment]
i talk about trigger...it's not firing
i don't want to use chat
new player also can open chat
why this trigger needed?

**Comment by JulianUO** [comment]
Let me explain again...

The trigger is fired when the ChatButton packet is received.
The Chat packet is only sent the first time the player tries to open the chat menu, because they don't have the name registered on the server. After that, the client won't send the packet anymore. This is what happens on newest client.

Anyway, the trigger is fired everytime the packet is received.
The chat will be open no matter what RETURN value you use, because it is internal on the client.

**Comment by Seokotov** [comment]
and so, why needed this trigger?

**Comment by JulianUO** [comment]
Backwards compatibility. Plus can be used to register char name for the first time.
You can close it and if you need any kind of help you can ask in the discord channel, as always :D

**Comment by cbnolok** [comment]
I confirm what Julian said, the packet is sent only once, so sphere can't know when a newer client presses that button.
