### ISSUE TITLE
itemunequip trigger doesnt return correct armor value

### ISSUE THREAD

**Issue by azmanomer** [Sphereserver/Source-experimental#35]
Example :  i_agapite_platemail_arms  armor value: 37
under player events:
on @itemunequip
say <ar>  //this one show not updated armor value like if u have 5 armor while wearing armor and it become 0 when u equip it but it say "5" even i tried with "timerf 5,say <ar>" its still saying "5"

**Comment by cbnolok** [comment]
This is the expected behavior, since @Unequip and @ItemUnequip are called **when** an item is unequipped, not **after** it is equipped, in fact the armor calculations are done after that trigger call (in CChar::OnRemoveObj, CCharAct.cpp).
If you need it, we can think about adding the @(Item)AfterEquip and @(Item)AfterUnequip triggers.

**Comment by azmanomer** [comment]
so @itemunequip and @unequip is called when i try to remove my armor right? but still i couldnt understand why timerf 5,say <ar> still returning wrong value

**Comment by cbnolok** [comment]
Right. The TIMERF behavior is explained because the parser parses the whole line before actually executing it, so if AR == 5, TIMERF SAY <AR> becomes TIMERF SAY 5, then it's saved and executed later as SAY 5.

**Comment by azmanomer** [comment]
oh thx for explanation
